### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MasterCryptoFarmBot#42]
```
Task exception was never retrieved
future: <Task finished name='Task-636' coro=<Session.restart() done, defined at C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\session\session.py:182> exception=ProgrammingError('Cannot operate on a closed database.')>
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\session\session.py", line 184, in restart
    await self.start()
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\session\session.py", line 149, in start
    raise e
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\session\session.py", line 124, in start
    api_id=await self.client.storage.api_id(),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\storage\sqlite_storage.py", line 195, in api_id
    return self._accessor(value)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\storage\sqlite_storage.py", line 189, in _accessor
    return self._get() if value == object else self._set(value)
           ^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\storage\sqlite_storage.py", line 175, in _get
    return self.conn.execute(
           ^^^^^^^^^^^^^^^^^^
sqlite3.ProgrammingError: Cannot operate on a closed database.
Task exception was never retrieved
future: <Task finished name='Task-634' coro=<Session.restart() done, defined at C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\session\session.py:182> exception=ProgrammingError('Cannot operate on a closed database.')>
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\session\session.py", line 184, in restart
    await self.start()
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\session\session.py", line 149, in start
    raise e
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\session\session.py", line 124, in start
    api_id=await self.client.storage.api_id(),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\storage\sqlite_storage.py", line 195, in api_id
    return self._accessor(value)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\storage\sqlite_storage.py", line 189, in _accessor
    return self._get() if value == object else self._set(value)
           ^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\storage\sqlite_storage.py", line 175, in _get
    return self.conn.execute(
           ^^^^^^^^^^^^^^^^^^
sqlite3.ProgrammingError: Cannot operate on a closed database.
[MasterCryptoFarmBot] [02:56:06] [MCF_Seed] [INFO] ✔️ Pyrogram session xxx has been disconnected successfully!
[MasterCryptoFarmBot] [02:56:06] [MCF_Seed] [INFO] xxx | 🌱 Tag has been added to the last name!
Task exception was never retrieved
future: <Task finished name='Task-633' coro=<Session.restart() done, defined at C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\session\session.py:182> exception=ProgrammingError('Cannot operate on a closed database.')>
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\session\session.py", line 184, in restart
    await self.start()
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\session\session.py", line 149, in start
    raise e
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\session\session.py", line 124, in start
    api_id=await self.client.storage.api_id(),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\storage\sqlite_storage.py", line 195, in api_id
    return self._accessor(value)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\storage\sqlite_storage.py", line 189, in _accessor
    return self._get() if value == object else self._set(value)
           ^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\storage\sqlite_storage.py", line 175, in _get
    return self.conn.execute(
           ^^^^^^^^^^^^^^^^^^
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

**Comment by tboy1337** [comment]
```
[MasterCryptoFarmBot] [02:59:15] [MCF_Seed] [INFO] 📗 xxx task Play W-Coin started and marked as completed!
[MasterCryptoFarmBot] [02:59:15] [MCF_Seed] [ERROR] └─ ❌ Event loop is closed
[MasterCryptoFarmBot] [02:59:15] [MCF_Seed] [INFO] └─ ❌ xxx session failed to get app url!
[MasterCryptoFarmBot] [02:59:15] [MCF_Seed] [INFO] 💻 Disconnecting Pyrogram session xxx ...
```

**Comment by tboy1337** [comment]
```
Exception in thread Thread-12 (<lambda>):
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xxx\MasterCryptoFarmBot\modules\MCF_Seed\bot.py", line 455, in <lambda>
    target=lambda: asyncio.run(
                   ^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\xxx\MasterCryptoFarmBot\modules\MCF_Seed\bot.py", line 236, in handle_accounts
    await process_pg_account(account, bot_globals, log, group_id)
  File "C:\Users\xxx\MasterCryptoFarmBot\modules\MCF_Seed\bot.py", line 161, in process_pg_account
    await fb.run()
  File "C:\Users\xxx\MasterCryptoFarmBot\modules\MCF_Seed\FarmBot\FarmBot.py", line 327, in run
    await task.do_tasks(self.bot_globals, tgAccount=self.tgAccount)
  File "C:\Users\xxx\MasterCryptoFarmBot\modules\MCF_Seed\FarmBot\core\Task.py", line 127, in do_tasks
    await tg.getWebViewData()
  File "C:\Users\xxx\MasterCryptoFarmBot\mcf_utils\tgPyrogram.py", line 198, in getWebViewData
    async with connect_pyrogram(
  File "C:\Program Files\Python312\Lib\contextlib.py", line 217, in __aexit__
    await anext(self.gen)
  File "C:\Users\xxx\MasterCryptoFarmBot\mcf_utils\tgPyrogram.py", line 140, in connect_pyrogram
    await tgClient.disconnect()
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\methods\auth\disconnect.py", line 38, in disconnect
    await self.session.stop()
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\session\session.py", line 165, in stop
    await self.ping_task
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\session\session.py", line 276, in ping_worker
    await asyncio.wait_for(self.ping_task_event.wait(), self.PING_INTERVAL)
  File "C:\Program Files\Python312\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\locks.py", line 212, in wait
    await fut
asyncio.exceptions.CancelledError
```

**Comment by tboy1337** [comment]
```
[MasterCryptoFarmBot] [03:02:18] [MCF_Seed] [INFO] 🟡 xxx task Boost SEED's blossom not supported...
```

**Comment by masterking32** [comment]
All the errors were fixed and `[MasterCryptoFarmBot] [03:02:18] [MCF_Seed] [INFO] 🟡 xxx task Boost SEED's blossom not supported...` is fine, you need to link wallet and pay with wallet and finish it manually.
