### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MasterCryptoFarmBot#44]
```
Task exception was never retrieved
future: <Task finished name='Task-180' coro=<Session.restart() done, defined at C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\session\session.py:182> exception=ProgrammingError('Cannot operate on a closed database.')>
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\session\session.py", line 184, in restart
    await self.start()
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\session\session.py", line 149, in start
    raise e
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\session\session.py", line 124, in start
    api_id=await self.client.storage.api_id(),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\storage\sqlite_storage.py", line 195, in api_id
    return self._accessor(value)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\storage\sqlite_storage.py", line 189, in _accessor
    return self._get() if value == object else self._set(value)
           ^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Roaming\Python\Python312\site-packages\pyrogram\storage\sqlite_storage.py", line 175, in _get
    return self.conn.execute(
           ^^^^^^^^^^^^^^^^^^
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

**Comment by tboy1337** [comment]
```
[MasterCryptoFarmBot] [10:18:08] [MCF_PocketFi] [INFO] ❌ Pyrogram session acc1 connection has been cancelled!
[MasterCryptoFarmBot] [10:18:08] [MCF_PocketFi] [INFO] ❌ Pyrogram session acc2 connection has been cancelled!
[MasterCryptoFarmBot] [10:18:08] [MCF_PocketFi] [INFO] 💻 Disconnecting Pyrogram session acc1 ...
[MasterCryptoFarmBot] [10:18:08] [MCF_PocketFi] [INFO] ❌ Pyrogram session acc3 connection has been cancelled!
[MasterCryptoFarmBot] [10:18:08] [MCF_PocketFi] [INFO] 💻 Disconnecting Pyrogram session acc2 ...
[MasterCryptoFarmBot] [10:18:08] [MCF_PocketFi] [INFO] ❌ Pyrogram session acc4 connection has been cancelled!
[MasterCryptoFarmBot] [10:18:08] [MCF_PocketFi] [INFO] 💻 Disconnecting Pyrogram session acc3 ...
[MasterCryptoFarmBot] [10:18:08] [MCF_PocketFi] [INFO] ❌ Failed to run acc2 account!
[MasterCryptoFarmBot] [10:18:08] [MCF_PocketFi] [INFO] 💻 Disconnecting Pyrogram session acc4 ...
[MasterCryptoFarmBot] [10:18:08] [MCF_PocketFi] [INFO] ❌ Failed to run acc3 account!
```

**Comment by tboy1337** [comment]
```
[MasterCryptoFarmBot] [10:18:56] [MCF_Seed] [ERROR] 🔴  POST Request Error: https://elb.seeddao.org/api/v1/bird-feed Response code: 400
[MasterCryptoFarmBot] [10:18:56] [MCF_Seed] [ERROR] ⭕ xxx failed to feed bird!
```

**Comment by tboy1337** [comment]
```
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [INFO] [Playground] 🟡  Unable to send request, retrying...
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=1306, microseconds=270589), 'exception': None, 'extra': {}, 'file': (name='Playground.py', path='C:\\Users\\FARM\\MasterCryptoFarmBot\\modules\\MCF_HamsterKombat\\utilities\\Playground.py'), 'function': 'http_request', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 357, 'message': '[Playground] 🟡  Unable to send request, retrying...', 'module': 'Playground', 'name': 'utilities.Playground', 'process': (id=5504, name='MainProcess'), 'thread': (id=5432, name='Thread-60 (handle_request)'), 'time': datetime(2024, 10, 9, 10, 38, 36, 205630, tzinfo=datetime.timezone(datetime.timedelta(seconds=3600), 'GMT Summer Time'))}
[MasterCryptoFarmBot] [10:38:36] [MCF_HamsterKombat] [ERROR] [Playground] 🔴 Error generating promo key: maximum recursion depth exceeded
```

**Comment by tboy1337** [comment]
Also I get many of these errors when the bot first starts.

```
[MasterCryptoFarmBot] [10:45:07] [MCF_Seed] [INFO] └─ ❌ xxx session failed to get web view data!
[MasterCryptoFarmBot] [10:45:07] [MCF_Seed] [ERROR] ❌ database is locked
[MasterCryptoFarmBot] [10:45:07] [MCF_Seed] [ERROR] └─ ❌ Account xxx from group 24 is not ready! Unable to retrieve WebApp data.
```

**Comment by masterking32** [comment]
Invalid issue, Don't make an issue like that to paste errors without any details, you need to create one issue per error.
By the way, all of them come from pyrograms or account issues and connections.
