### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MasterCryptoFarmBot#50]
```
exception calling callback for <Future at 0x1bae0722750 state=cancelled>
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\concurrent\futures\_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "C:\Program Files\Python312\Lib\asyncio\futures.py", line 396, in _call_check_cancel
    source_loop.call_soon_threadsafe(source.cancel)
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 840, in call_soon_threadsafe
    self._check_closed()
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 541, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

 - OS: Windows 10 Pro x64
 - Browser: Firefox Default
 - Version: 1.5.1

**Comment by tboy1337** [comment]
Ah ok, I didnt do anything though, im just watching the bot and posting issues xD

**Comment by masterking32** [comment]
issue template is not valid ...

**Comment by tboy1337** [comment]
What do you mean issue template is invalid, you have said this a few times now, i have supplied all information you could need that is requested in the template and also the template is a mess and needs to be updated
