### ISSUE TITLE
MCF_PocketFi Bug

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MasterCryptoFarmBot#58]
Only the PocketFi module was running when the bug happened, all others were waiting to start again.

```
2024-10-12 22:27:36 Task exception was never retrieved
2024-10-12 22:27:36 future: <Task finished name='Task-419' coro=<Session.restart() done, defined at /usr/local/lib/python3.12/site-packages/pyrogram/session/session.py:182> exception=ProgrammingError('Cannot operate on a closed database.')>
2024-10-12 22:27:36 Traceback (most recent call last):
2024-10-12 22:27:36   File "/usr/local/lib/python3.12/site-packages/pyrogram/session/session.py", line 184, in restart
2024-10-12 22:27:36     await self.start()
2024-10-12 22:27:36   File "/usr/local/lib/python3.12/site-packages/pyrogram/session/session.py", line 149, in start
2024-10-12 22:27:36     raise e
2024-10-12 22:27:36   File "/usr/local/lib/python3.12/site-packages/pyrogram/session/session.py", line 124, in start
2024-10-12 22:27:36     api_id=await self.client.storage.api_id(),
2024-10-12 22:27:36            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-12 22:27:36   File "/usr/local/lib/python3.12/site-packages/pyrogram/storage/sqlite_storage.py", line 195, in api_id
2024-10-12 22:27:36     return self._accessor(value)
2024-10-12 22:27:36            ^^^^^^^^^^^^^^^^^^^^^
2024-10-12 22:27:36   File "/usr/local/lib/python3.12/site-packages/pyrogram/storage/sqlite_storage.py", line 189, in _accessor
2024-10-12 22:27:36     return self._get() if value == object else self._set(value)
2024-10-12 22:27:36            ^^^^^^^^^^^
2024-10-12 22:27:36   File "/usr/local/lib/python3.12/site-packages/pyrogram/storage/sqlite_storage.py", line 175, in _get
2024-10-12 22:27:36     return self.conn.execute(
2024-10-12 22:27:36            ^^^^^^^^^^^^^^^^^^
2024-10-12 22:27:36 sqlite3.ProgrammingError: Cannot operate on a closed database.
```

OS: Linux
Version: 1.5.1

**Comment by AmirhN1382** [comment]
https://docs.pyrogram.org/faq/sqlite3-operationalerror-database-is-locked
i assume you have internet issues. check the link there are workarunds.
